# Generated by Django 4.2.2 on 2023-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name_plural': 'students'},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='student_images/'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
